apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-app
spec:
  template:
    spec:
      containers:
      - name: my-app
        env:
          - name: foo
            value: we-are-in-dev
          - name: pr
            value: __PR_NUMBER
        envFrom:
          - configMapRef:
              name: app-config
          - secretRef:
              name: credentials
